require: rubocop-rspec
AllCops:
  Exclude:
    - "db/schema.rb"
    - "bin/**"
  RunRailsCops: true

Style/StringLiterals:
  EnforcedStyle: "double_quotes"

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
